#+title: Readme
#+author: Dylan Beebe
#+options: ^:nil
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/setup/html-theme-readtheorg.setup

* General

This application's purpose is to provide the individual user with a succint interface to record their vehicles' mileage logs and fiurther relay information such as fuel efficiency.

* Design

** Requirements

*** Functional Requirements

- CRUD Vehicle

- CRUD Mileage

- CRUD Mileage Attachment

- Notify user in new mileage UI if location accuracy is poor or unavailable.

- Notify user in new mileage UI if tank is not full.

- Compute "Price per Gallon" in mileage UI when viewing or creating new mileage records.

- Compute and display average MPG in vehicle UI.

- Render latest (non-exported) mileage records in vehicle UI indicating their non-exported status.

- Export latest (non-exported) or custom range of mileage records.

*** Non-functional Requirements

- Illustrate core user workflows using PlantUML.

- [[https://developer.android.com/topic/architecture][Maintainable app architecture]] utilizing [[https://developer.android.com/topic/architecture/recommendations][best practices and recommendations]].

- Version control source code using Git.

- Publish source code in public GitHub repo under GPLv3 license.

- Test-driven development of data layer comprising integration tests of CRUD and ViewModel state holders, and unit tests of core business logic (i.e. average MPG interpolation for non-full-tank mileage records).

- Publish on Play Store with modest convenience fee.

** Language/SDK

- Android application written in Kotlin.

- Android 8.1 (Oreo), SDK 27

** Frameworks/Technology

- Room (SQLite3 abstraction) database for offline data caching (future remote sync possibly with Firebase).

- Jetpack Compose instead of views.

* Implementation

** Entity Relationship Diagram

[[file:./diagrams/erd.svg]]

#+begin_src plantuml :file diagrams/erd.svg :tangle diagrams/erd.puml :exports none :results none
@startuml

entity "vehicle" as v {
        ,* **String : vehicleID <<PK>>**
        --
        ,* String : nickname
        String : make
        String : model
        Int : modelYear
        String : plate
}


entity "mileage" as m {
        ,* **String : mileageID <<PK>>**
        --
        ,* String : timestamp
        Double : latitude
        Double : longitude
        ,* Double : odometerMiles
        ,* Double : volumeGallons
        ,* Boolean : isFullTank
        ,* Enum : fuelType
        ,* Boolean : isTopTier
        ,* Double : totalDollars
        String : journal
        ,* boolean : isExported
        ,* **String : vehicle <<FK>>**
        ..
        <<unique>> (vehicle, timestamp)
}

entity "mileage_attachment" as ma {
        ,* **String : attachmentID <<PK>>**
        --
        ,* String : filepath
        ,* **String : mileage <<FK>>**
}

enum "fuelType" as ft {
        REGULAR
        PLUS
        PREMIUM
        E85
        DIESEL
}

v ||..o{ m
m ||..o{ ma

@enduml
#+end_src

** Average MPG Interpolation

:TODO: Determine what sort of interpolation algorithm shall be applied in this case.

** Export Mileage Records

The user must be able to quickly export the latest (non-exported) mileage records, and further select a custom date range of mileage records to export.

The user should have the options of exporting mileage records as plain CSV or JSON.

The application delegates the mode of exportation to any system activity (i.e. email, SMS, etc).

** Workflows

* Future

** User/Firebase/et al Sync

To begin with, this is a device-local, single user application. If this app suddenly gains traction there would be cause to upgrade this model to a centralized cloud storage to keep user data safe during device migrations/local data loss.

** Lat/Lon + Timestamp Business Delineations

Currently the only way to infer what business the user filled up at would be to snap a picture of the receipt, or else. My thought is that lat/lon could be used to determine, agains public record, what business the fillup takes place at using a given lat/lon and date and time combination. Maybe a pipedream but it seems like it should be possible now at least.

** Formatted PDF Mileage Exports

The user would have the additional option of exportting a formatted report of either their latest (non-exported) mileage logs, or a custom date range. See [[https://github.com/officialBeebe/ChoreBuddy][Chore Buddy]] for formatting details.
